In [6]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [7]:
employees = {
    'Emp_ID': range(1001, 1021),
    'Name': [
        'Ali', 'Sara', 'Umer', 'Hina', 'Bilal', 'Ayesha', 'Raza', 'Mona', 'Danish', 'Tuba',
        'Kashif', 'Iqra', 'Ahmed', 'Nida', 'Owais', 'Farah', 'Zain', 'Mehak', 'Haris', 'Amna'
    ],
    'Dept_ID': [101,102,103,104,105,101,102,103,104,105,101,102,103,104,105,101,102,103,104,105],
    'Salary': [
        70000, 82000, 60000, 90000, 75000, 71000, 88000, 64000, 94000, 77000,
        73000, 85000, 62000, 91000, 76000, 70500, 89500, 65000, 93000, 78000
    ],
    'Join_Year': [
        2018,2019,2020,2018,2017,2019,2018,2021,2022,2020,
        2017,2018,2019,2021,2022,2023,2019,2020,2021,2022
    ]
}

employees_table_df = pd.DataFrame(employees)
employees_table_df

    Emp_ID    Name  Dept_ID  Salary  Join_Year
0     1001     Ali      101   70000       2018
1     1002    Sara      102   82000       2019
2     1003    Umer      103   60000       2020
3     1004    Hina      104   90000       2018
4     1005   Bilal      105   75000       2017
5     1006  Ayesha      101   71000       2019
6     1007    Raza      102   88000       2018
7     1008    Mona      103   64000       2021
8     1009  Danish      104   94000       2022
9     1010    Tuba      105   77000       2020
10    1011  Kashif      101   73000       2017
11    1012    Iqra      102   85000       2018
12    1013   Ahmed      103   62000       2019
13    1014    Nida      104   91000       2021
14    1015   Owais      105   76000       2022
15    1016   Farah      101   70500       2023
16    1017    Zain      102   89500       2019
17    1018   Mehak      103   65000       2020
18    1019   Haris      104   93000       2021
19    1020    Amna      105   78000       2022

In [11]:
departments = {
    'Dept_ID': [101,102,103,104,105,106],
    'Dept_Name': ['HR','IT','Finance','Marketing','Sales','Operations'],
    'Manager': ['Faisal','Asma','Kamran','Tariq','Sadia','Hassan'],
    'Location': ['Lahore','Karachi','Islamabad','Lahore','Karachi','Faisalabad']
}
department_table_df = pd.DataFrame(departments)
department_table_df

   Dept_ID   Dept_Name Manager    Location
0      101          HR  Faisal      Lahore
1      102          IT    Asma     Karachi
2      103     Finance  Kamran   Islamabad
3      104   Marketing   Tariq      Lahore
4      105       Sales   Sadia     Karachi
5      106  Operations  Hassan  Faisalabad

In [ ]:
employees_table_df.merge(department_table_df, left_on='Emp_ID', right_on)